// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAmSCEx00shnwWHiPxh1d_Kgia1DOFMzI',
    appId: '1:948928943485:web:5d96c2269c0b7a6909a814',
    messagingSenderId: '948928943485',
    projectId: 'smart-plantation-fyp',
    authDomain: 'smart-plantation-fyp.firebaseapp.com',
    storageBucket: 'smart-plantation-fyp.appspot.com',
    measurementId: 'G-9D8DZPX865',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLifdMXwKhxpqplTGb5hmVGw_CHuq03GQ',
    appId: '1:948928943485:android:67f6c243be97b08209a814',
    messagingSenderId: '948928943485',
    projectId: 'smart-plantation-fyp',
    storageBucket: 'smart-plantation-fyp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZOD0japCBUOOEzAZhippqoMiAu3HQBq0',
    appId: '1:948928943485:ios:1c84ffb5ebafefbf09a814',
    messagingSenderId: '948928943485',
    projectId: 'smart-plantation-fyp',
    storageBucket: 'smart-plantation-fyp.appspot.com',
    iosClientId: '948928943485-n5kupla0422bllgacs5lje3kggbb6a5u.apps.googleusercontent.com',
    iosBundleId: 'com.example.assignmentStarter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZOD0japCBUOOEzAZhippqoMiAu3HQBq0',
    appId: '1:948928943485:ios:1c84ffb5ebafefbf09a814',
    messagingSenderId: '948928943485',
    projectId: 'smart-plantation-fyp',
    storageBucket: 'smart-plantation-fyp.appspot.com',
    iosClientId: '948928943485-n5kupla0422bllgacs5lje3kggbb6a5u.apps.googleusercontent.com',
    iosBundleId: 'com.example.assignmentStarter',
  );
}
